language: cpp

compiler:
    - gcc

before_script:
    -  sudo add-apt-repository ppa:mapnik/boost -y
    -  sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    -  sudo add-apt-repository ppa:fcitx-team/nightly -y
    -  wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -
    -  echo deb http://dl.hhvm.com/ubuntu precise main | sudo tee /etc/apt/sources.list.d/hhvm.list
    -  sudo apt-get update
    -  sudo apt-get -y install hhvm-dbg hhvm-dev cmake check libpcre3 libpcre3-dev libjemalloc-dev libjemalloc1 build-essential libtool automake autoconf pkg-config gcc-4.8 g++-4.8 libboost1.49-dev libboost-regex1.49-dev libboost-system1.49-dev libboost-program-options1.49-dev libboost-filesystem1.49-dev libboost-thread1.49-dev libgoogle-glog-dev libgoogle-glog0
    -  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
    -  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
    -  sudo update-alternatives --set gcc /usr/bin/gcc-4.8
script:
    -  HPHPIZE_PATH=/usr/bin/hphpize ./build.sh
    -  HHVM_BIN=/usr/bin/hhvm ./run-tests.sh
